services:
  whatsapp-service:
    build: .
    container_name: whatsapp-service
    restart: always
    ports:
      - "3030:3030"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      - ./data/auth:/app/.wwebjs_auth
      - ./data/cache:/app/.wwebjs_cache
